= Bernard Teo Zhi Yi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:1H: #
:stylesheet: alternate-btzy.css

== PROJECT: Deadline Manager

:sectnums:
:sectnumlevels: 6

This portfolio serves to document my contributions to Deadline Manager - our 2^nd^ year software engineering project.  We worked as a team of 5 people to create Deadline Manager, which is based on https://github.com/nus-cs2103-AY1819S1/addressbook-level4[Address Book (Level 4)].  We were constrained to use a command line interface (CLI) and were given 6 weeks to work on our application.

Deadline Manager is a desktop deadline manager application designed for students in NUS School of Computing.  It is optimized to be easy to use, but yet give users great control and flexibility.  It is written in Java.  Visit our https://github.com/CS2103-AY1819S1-W17-4/main[project page] to try our application.

== Summary of contributions

* *Major enhancement*: Added an *expressive but terse way to filter tasks*.
** What it does: It allows the user to filter tasks using a filter expression.  Filter expressions can be composed from other filter expressions using "AND", "OR", and "NOT" logical operators, and users can optionally specify which attribute in the task to search against.
** Justification: With an expected large number of tasks in our application, users need to be able to view a subset of tasks that are relevant to them so that they can make sense of their deadlines.  The ability to compose filter expressions adds great flexibility which is useful when filtering by more than one field.  The ability to export and share tasks further necessitates an expressive filter command that can filter precisely those tasks that the user would like to export.
** Highlights: Firstly, the implementation features a full expression parser that parses arbitrary levels of parentheses and respects operator precedence.  Secondly, many different attribute of a tasks (of varying type, e.g. textual, numeric, date, sets) were made filterable.  Thirdly, each attribute could be compared in multiple ways (e.g. users can specify tasks to be filtered if they are due earlier than a given date, later than a given date, or exactly on a given date).  Fourthly, text can be quoted in order to search for a whole phrase.  Many design considerations have also been made to simplify its use: Specifying the attribute (of the task) for filtering is optional (when unspecified it searches all eligible attributes), a filter expression can use an attribute-specific default comparison, and "AND" operators may be omitted.  These design considerations greatly reduce the cognitive burden for simple use cases, but yet retain the ability to provide fine-grained control where needed.

* *Minor enhancement*: Added the deadline attribute to tasks.
** What it does: The deadline attribute contains the due date of the task, and this is essential to the core functionality of the deadline manager.
** Highlights: The implementation deals with the parsing and validating of dates.  Furthermore, it integrates into other commands that need to specify a deadline.  This attribute was also integrated throughout the storage-related code so that the deadline can be exported to a file and imported into another instance of Deadline Manager.

* *Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=btzy[CS2103T Project Code Dashboard]

* *Other contributions*:

** Project management: Contributed to user stories on GitHub issue tracker ([underline]#{1H}9#, [underline]#{1H}10#, [underline]#{1H}11#, [underline]#{1H}12#, [underline]#{1H}21#, [underline]#{1H}22#); managed milestones on GitHub
** Enhancements to existing features: Overhauled the existing command parser to use a custom-made string tokenizer shared with the filter expression parser in order to support additional features such as quoted strings.  Almost all commands now depend on this string tokenizer.
** Community:
*** Reviewed pull requests (with non-trivial review comments): https://github.com/CS2103-AY1819S1-W17-4/main/pull/92[#92], https://github.com/CS2103-AY1819S1-W17-4/main/pull/154[#154]
*** Contributed to forum discussions (examples:  https://github.com/nus-cs2103-AY1819S1/forum/issues/127[1])


== Contributions to the User Guide


|===
|_Given below are excerpts of sections that I contributed to the user guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide-btzy.adoc[tag=filter-overview]

include::../UserGuide-btzy.adoc[tag=filter-simplified]

|===
|_Details of the simplified filter syntax have been omitted for brievity.  Please see our https://cs2103-ay1819s1-w17-4.github.io/main/UserGuide.html#simplified-filter-syntax[user guide] for more details and command examples._
|===

include::../UserGuide-btzy.adoc[tag=filter-field]

The operator `:` is known as the *convenience* operator -- it is an alias for the operator that intuitively "does what you expect" for the given `key`.

|===
|_The behaviour for each given `key` is documentated in our https://cs2103-ay1819s1-w17-4.github.io/main/UserGuide.html#controlling-the-field-being-matched[user guide].  Ample examples are also available there._
|===

==== Composing filter predicates

Filter predicates may be combined using AND, OR, and NOT operators, as well as any level of parantheses.  This feature gives ultimate flexibility to the filter command.

For example, `filter n:assignment | (p:3 & t:CS2101)` will return a subset of the current list of tasks that have a name that contains "assignment", or have priority at least 3 and contains tag "CS2101".

|===
|_For more explanation and examples on using composition of filter predicates effectively, please visit our https://cs2103-ay1819s1-w17-4.github.io/main/UserGuide.html#composing-filter-predicates[user guide]._
|===

include::../UserGuide-btzy.adoc[tag=filter-set]

|===
|_For more examples, please visit our https://cs2103-ay1819s1-w17-4.github.io/main/UserGuide.html#set-based-extensions-for-filter-predicates[user guide]._
|===

include::../UserGuide-btzy.adoc[tag=filter-errors]

|===
|_Many of my contributions to the user guide have been omitted for brevity.  Please visit https://cs2103-ay1819s1-w17-4.github.io/main/UserGuide.html#filtering-a-list-of-tasks-code-filter-code[this link] for the full user guide._
|===

== Contributions to the Developer Guide

|===
|_Given below are excerpts of sections that I contributed to the developer guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide-btzy.adoc[tag=filter-ppp-prefix]
include::../DeveloperGuide-btzy.adoc[tag=filter-ppp-overview-header]

|===
|_For a more detailed overview of the filter feature, please visit our https://cs2103-ay1819s1-w17-4.github.io/main/DeveloperGuide.html#overview[developer guide]._
|===

include::../DeveloperGuide-btzy.adoc[tag=filter-overview-condensed]

|===
|_For more details on the general string tokenizer that was specially designed for the filter command, please visit our https://cs2103-ay1819s1-w17-4.github.io/main/DeveloperGuide.html#string-tokenizer[developer guide]._
|===

==== Boolean expression parser

|===
|_The boolean expression parser uses the shunting yard algorithm to compose NOT, AND, and OR operators, and respects operator precedence.  For more information, please visit our https://cs2103-ay1819s1-w17-4.github.io/main/DeveloperGuide.html#boolean-expression-parser[developer guide]._
|===

==== Filter unit parser

The filter unit parser is written as a lambda expression inside the `FilterCommandParser` class.  This lambda expression then calls `FilterCommandParser#createFilterUnit`, which contains most of the logic for the filter unit parser.

include::../DeveloperGuide-btzy.adoc[tag=filter-unit-parser-extract]

|===
|_The extended full syntax for sets and the simplified syntax are explained in our https://cs2103-ay1819s1-w17-4.github.io/main/DeveloperGuide.html#filter-unit-parser[developer guide]._
|===

include::../DeveloperGuide-btzy.adoc[tag=filter-unit-parser-diagram]

|===
|_More explanation on the "field identifier", "filter operator", "set operator", and "test phrase" are available in our https://cs2103-ay1819s1-w17-4.github.io/main/DeveloperGuide.html#field-identifier[developer guide].  Documentation for the field-specific parser is also available there.  Please follow the link for more information._
|===

==== Error messages

include::../DeveloperGuide-btzy.adoc[tag=filter-error-messages]

In the diagram above, the [blue]#*blue*# classes are exceptions thrown by `StringTokenizer`, while the [red]#*red*# classes are exceptions thrown by `BooleanExpressionParser`.

|===
|_More explanation on the use of `TokenizationInvalidPredicateException` is available in our https://cs2103-ay1819s1-w17-4.github.io/main/DeveloperGuide.html#error-messages[developer guide]._
|===

include::../DeveloperGuide-btzy.adoc[tag=filter-design-considerations-header]

include::../DeveloperGuide-btzy.adoc[tag=filter-design-considerations-convenience]

include::../DeveloperGuide-btzy.adoc[tag=filter-design-considerations-exceptions]

|===
|_Many of my contributions to the developer guide have been omitted for brevity.  Please visit https://cs2103-ay1819s1-w17-4.github.io/main/DeveloperGuide.html#filter-feature[this link] for the full developer guide._
|===
